### ISSUE TITLE
Needs random jitter

### ISSUE THREAD

**Issue by zenspider** [ashirazi/rescue_me#1]
We'd totally use this package if it wasn't purely exponential. Having a service hammered to the point of failure, only to have everyone back off for the same amount of time and hammer it again isn't helpful. Having them spread out randomly would alleviate a lot of problems. Jitter should probably be bound between the previous and current exponent.

**Comment by ashirazi** [comment]
Is this a real issue?
The reason I ask is that most MTAs have a relatively simple retry strategy (X min between retries, give up after Y). I have also seen NCBI employ this strategy to handle the high load of searches they get (http://blast.ncbi.nlm.nih.gov/).
I would like to see some research or empirical evidence that this approach is sub-optimal to one that employs jitter.

**Comment by zenspider** [comment]
This isn't an MTA and MTAs are generally 1:M, not M:1. There is a big difference on how that works and how it impacts others. We'd be using this across multiple machines that will be synchronized (think cron + ntpd) and talking to a single service. Hammering at an exponential backoff interval in parallel is not good.

For references:
- http://en.wikipedia.org/wiki/Exponential_backoff
- http://en.wikipedia.org/wiki/Network_congestion_avoidance

**Comment by zenspider** [comment]
Project seems abandoned (and not interested). Closing.
